item/urls.py
from django.conf.urls import url
from django.urls import include,path
from . import views

app_name='item'

urlpatterns = [
	path('',views.display_item,name='item'),
    path('create/',views.create_item,name='create-item'),
]

silau/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('items/', include('item.urls')),
    path('daftarlaundry/', include('daftarlaundry.urls')),
    path('dpay/', include('topup.urls')),
    path('layanan/', include('layanan.urls')),
    path('transaksilaundry/', include('transaksilaundry.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls'))
]

transaksilaundry/urls.py
from django.urls import path

from . import views

app_name = "transaksilaundry"

urlpatterns = [
    path('', views.view_transaksi,name='view_transaksi'),
    path('update_transaksi/<str:email>,<str:tanggal>', views.update_transaksi, name='update_transaksi'),
    path('delete_transaksi/<str:email>,<str:tanggal>', views.delete_transaksi_laundry, name='delete_transaksi'),
    path('create/', views.create_transaksi, name='create_transaksi'),
    path('view_status/', views.view_status, name='view_status'),
    path('update_status/<str:email>,<str:tanggal_transaksi>', views.update_status, name='update_status'),
    path('delete_status/<str:email>,<str:tanggal_transaksi>', views.delete_status_transaksi_laundry, name='delete_status'),
    
]

transaksilaundry/models.py
from django.db import models

# Create your models here.

transaksilaundry/forms.py
from django import forms

class CreateTransaksi(forms.Form):
    email = forms.ChoiceField(label="Email",choices=[], help_text='\n')
    berat = forms.IntegerField(label="Berat",help_text='\n')
    total_item = forms.IntegerField(label="Total Item", help_text='\n')
    kode_layanan = forms.ChoiceField(label="Kode Layanan", choices=[], help_text='\n')
    kode_tarif= forms.ChoiceField(label="Kode Tarif", choices=[], help_text='\n')
    Total_Biaya=forms.IntegerField(label="Total Biaya", help_text='\n')
    email_staf=forms.ChoiceField(label="Email Staf", choices=[], help_text='\n')
    email_kurir=forms.ChoiceField(label="Email Kurir", choices=[], help_text='\n')
    
class UpdateTransaksi(forms.Form):
    email = forms.ChoiceField(label="Email", choices=[], help_text='\n')
    tanggal= forms.DateField(label="Tanggal", help_text='\n')
    berat = forms.IntegerField(label="Berat", help_text='\n')
    total_item = forms.IntegerField(label="Total Item", help_text='\n')
    kode_layanan = forms.ChoiceField(label="Kode Layanan", choices=[], help_text='\n')
    kode_tarif= forms.ChoiceField(label="Kode Tarif", choices=[], help_text='\n')
    Total_Biaya=forms.IntegerField(label="Total Biaya", help_text='\n')
    email_staf=forms.ChoiceField(label="Email Staf", choices=[], help_text='\n')
    email_kurir=forms.ChoiceField(label="Email Kurir", choices=[], help_text='\n')
        
class UpdateStatus(forms.Form):
    email = forms.ChoiceField(label="Email", choices=[], help_text='\n')
    kode_status= forms.ChoiceField(label="kode Status", choices=[], help_text='\n')
    timestamp= forms.TimeField(label="Timestamp", help_text='\n')

        
        
        

transaksilaundry/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import CreateTransaksi,UpdateTransaksi,UpdateStatus
from django.db import connection
from datetime import date, datetime
import time
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.

def view_transaksi(request):
    if "email" not in request.session:
        return redirect('/auth/login')

    transaksi_raw = get_transaksi()
    response = {}
    response['is_staf'] = "is_staf" in request.session
    response['data'] = transaksi_raw
    return render(request,'transaksilaundry/view_transaksi.html',response)


def view_status(request):
    if "email" not in request.session:
        return redirect('/auth/login')

    status_transaksi_raw = get_status_transaksi()
    response = {}
    response['is_staf'] = "is_staf" in request.session
    response['data'] = status_transaksi_raw
    return render(request,'transaksilaundry/view_status.html',response)

@csrf_exempt
def update_transaksi(request,email,tanggal):
    if "is_staf" not in request.session:
        return redirect('/auth/unauthorized')
    if "email" not in request.session:
        return redirect('/auth/login')
    
    if(email != None):
        prefilled_data = get_email_pengguna_update(email,tanggal)
        response={}
        response['error']=False
        form = UpdateTransaksi(request.POST or None, initial={'email':email,'tanggal':tanggal,'berat':prefilled_data['berat'],'total_item':prefilled_data['total_item'],'kode_layanan':prefilled_data['kode_layanan'],'kode_tarif':prefilled_data['kode_tarif'],'Total_Biaya':prefilled_data['total_harga'],'email_staf':prefilled_data['email_staf'],'email_kurir':prefilled_data['email_kurir_antar']})
        form.fields['email'].disabled = True
        form.fields['tanggal'].disabled = True
        email = get_email_pengguna()
        kode_layanan = get_kode_layanan()
        kode_tarif = get_kode_tarif()
        email_staf = get_email_staf()
        email_kurir = get_email_kurir()  
        form.fields['email'].choices=email
        form.fields['kode_layanan'].choices=kode_layanan
        form.fields['kode_tarif'].choices=kode_tarif
        form.fields['email_staf'].choices=email_staf
        form.fields['email_kurir'].choices=email_kurir
        response['form'] = form
        
    if(request.method == "POST" and form.is_valid()):
        email = form.cleaned_data['email']
        tanggal=form.cleaned_data['tanggal']
        berat = form.cleaned_data['berat']
        total_item = form.cleaned_data['total_item']
        kode_layanan = form.cleaned_data['kode_layanan']
        kode_tarif= form.cleaned_data['kode_tarif']
        Total_Biaya=form.cleaned_data['Total_Biaya']
        email_staf=form.cleaned_data['email_staf']
        email_kurir=form.cleaned_data['email_kurir']
        cursor = connection.cursor()
        cursor.execute("set search_path to silau;")
        cursor.execute("update transaksi_laundry set email=%s, tanggal=%s, berat=%s, total_item=%s, kode_layanan=%s, kode_tarif=%s , total_harga=%s, email_staf=%s , email_kurir_antar=%s where email=%s and tanggal=%s", [email,tanggal,berat,total_item,kode_layanan,kode_tarif,Total_Biaya,email_staf,email_kurir,email,tanggal])
        return redirect('transaksilaundry:view_transaksi')

    return render(request, 'transaksilaundry/update_transaksi.html', {'form': form})

def delete_transaksi_laundry(request,email,tanggal):
        cursor = connection.cursor()
        cursor.execute("set search_path to silau;")
        cursor.execute("delete from transaksi_laundry where email=%s and tanggal=%s;",[email,tanggal])
        return redirect('transaksilaundry:view_transaksi')


def update_status(request,email,tanggal_transaksi):
    if "is_staf" not in request.session:
        return redirect('/auth/unauthorized')
    if "email" not in request.session:
        return redirect('/auth/login')
    
    if(email != None):
        prefilled_data = get_email_pengguna_update_status(email,tanggal_transaksi)
        response={}
        response['error']=False
        form = UpdateStatus(request.POST or None, initial={'email':email,'kode_status':prefilled_data['kode_status'],'timestamp':prefilled_data['timestamp']})
        form.fields['email'].disabled = True
        email = get_email_pengguna()
        kode_status = get_kode_status()
        form.fields['email'].choices=email
        form.fields['kode_status'].choices=kode_status
        response['form'] = form
        
    if(request.method == "POST" and form.is_valid()):
        email = form.cleaned_data['email']
        kode_status = form.cleaned_data['kode_status']
        timestamp=form.cleaned_data['timestamp']
        cursor = connection.cursor()
        cursor.execute("set search_path to silau;")
        cursor.execute("update status_transaksi set email=%s, kode_status=%s, timestamp=%s where email=%s and tanggal_transaksi=%s", [email,kode_status,timestamp,email,tanggal_transaksi])
        return redirect('transaksilaundry:view_status')

    return render(request, 'transaksilaundry/update_status.html', {'form': form})


def delete_status_transaksi_laundry(request,email,tanggal_transaksi):
        cursor = connection.cursor()
        cursor.execute("set search_path to silau;")
        cursor.execute("delete from status_transaksi where email=%s and tanggal_transaksi=%s;",[email,tanggal_transaksi])
        return redirect('transaksilaundry:view_status')
    
def create_transaksi(request):
    if "is_staf" not in request.session:
        return redirect('/auth/unauthorized')
    if "email" not in request.session:
        return redirect('/auth/login')
    response = {}
    response['error'] = False
    email = get_email_pengguna()
    kode_layanan = get_kode_layanan()
    kode_tarif = get_kode_tarif()
    email_staf = get_email_staf()
    email_kurir = get_email_kurir()
    form = CreateTransaksi(request.POST or None)   
    form.fields['email'].choices=email
    form.fields['kode_layanan'].choices=kode_layanan
    form.fields['kode_tarif'].choices=kode_tarif
    form.fields['email_staf'].choices=email_staf
    form.fields['email_kurir'].choices=email_kurir
    response['form'] = form
    
    if(request.method=="POST" and form.is_valid()):
        print(form.cleaned_data)
        email = form.cleaned_data['email']
        berat = form.cleaned_data['berat']
        total_item = form.cleaned_data['total_item']
        diskon =0
        kode_layanan = form.cleaned_data['kode_layanan']
        kode_tarif= form.cleaned_data['kode_tarif']
        email_staf=form.cleaned_data['email_staf']
        email_kurir=form.cleaned_data['email_kurir']
        harga=get_harga_layanan(kode_layanan)
        biaya_laundry=harga['harga']
        tanggal = date.today()
        waktu=datetime.now().time()
        biaya_antar=get_harga_tarif(kode_tarif)['harga']
        biaya_jemput=get_harga_tarif(kode_tarif)['harga']  
        Total_Biaya=form.cleaned_data['Total_Biaya']
        cursor = connection.cursor()
        cursor.execute("set search_path to silau;")
        cursor.execute("insert into transaksi_laundry(email,tanggal,berat,total_item,biaya_laundry,biaya_antar,biaya_jemput,diskon,total_harga,foto_pengambilan,kode_layanan,kode_tarif,email_staf,email_kurir_antar,email_kurir_jemput) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);",[email,tanggal,berat,total_item,biaya_laundry,biaya_antar,biaya_jemput,diskon,Total_Biaya,'http://dummyimage.com/213x199.bmp/5fa2dd/ffffff',kode_layanan,kode_tarif,email_staf,email_kurir,email_kurir])
        cursor.execute("insert into status_transaksi(email,tanggal_transaksi,kode_status,timestamp) values(%s,%s,%s,%s);",[email,tanggal,'S01',waktu])
        return redirect('transaksilaundry:view_transaksi')
    return render(request, 'transaksilaundry/create_transaksi.html', response)
    

def get_harga_layanan(kode):
    cursor = connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute("select harga from layanan where kode=%s;",[kode])
    res_dirty = fetch(cursor)
    return res_dirty[0]

def get_harga_tarif(kode):
    cursor = connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute("select harga from tarif_antar_jemput where kode=%s;",[kode])
    res_dirty = fetch(cursor)
    return res_dirty[0]

def get_email_pengguna_update(email,tanggal):
    cursor = connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute("select * from transaksi_laundry where email=%s and tanggal=%s;",[email,tanggal])
    res_dirty = fetch(cursor)
    return res_dirty[0]

def get_email_pengguna_update_status(email,tanggal):
    cursor = connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute("select * from status_transaksi where email=%s and tanggal_transaksi=%s;",[email,tanggal])
    res_dirty = fetch(cursor)
    return res_dirty[0]
    
def get_email_pengguna():
    query="""
    select email from pelanggan;
    """
    cursor=connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute(query)
    email_response = fetch(cursor)
    res=[]
    for email in email_response:
        temp = email['email']
        res.append((temp,temp,))
    return res


def get_kode_layanan():
    query="""
    select kode from layanan;
    """
    cursor=connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute(query)
    kode_layanan_response = fetch(cursor)
    res=[]
    for kode in kode_layanan_response:
        temp = kode['kode']
        res.append((temp,temp,))
    return res

def get_kode_status():
    query="""
    select kode from status;
    """
    cursor=connection.cursor()
    cursor.execute("set search_path to silau;")
    cursor.execute(query)
    kode_status_response = fetch(cursor)
    res=[]
    for kode in kode_status_response:
        temp = kode['kode']
        res.append((temp,temp,))
    return res

def get_kode_tarif():
    query="""

transaksilaundry/templates/transaksilaundry/create_transaksi.html
{% load static %}
{% if request.session.is_staf %}
{% include "base_staf_admin.html" %}
{% endif %}
{% if request.session.is_kurir %}
{% include "base_kurir.html" %}
{% endif %}
{% if request.session.is_user %}
{% include "base_pelanggan.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buat Transaksi</title>
</head>

<body>
    <h1>Buat Transaksi</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}    
        <button type="submit">Buat Transaksi</button>
    </form>
</body>
</html>

transaksilaundry/templates/transaksilaundry/update_status.html
{% load static %}
{% if request.session.is_staf %}
{% include "base_staf_admin.html" %}
{% endif %}
{% if request.session.is_kurir %}
{% include "base_kurir.html" %}
{% endif %}
{% if request.session.is_user %}
{% include "base_pelanggan.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Status Transaksi</title>
</head>

<body>
    <h1>Update Status Transaksi</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SUBMIT</button>
    </form>
</body>

</html>

transaksilaundry/templates/transaksilaundry/update_transaksi.html
{% load static %}
{% if request.session.is_staf %}
{% include "base_staf_admin.html" %}
{% endif %}
{% if request.session.is_kurir %}
{% include "base_kurir.html" %}
{% endif %}
{% if request.session.is_user %}
{% include "base_pelanggan.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Transaksi</title>
</head>

<body>
    <h1>Update Transaksi</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SUBMIT</button>
    </form>
</body>

</html>

transaksilaundry/templates/transaksilaundry/view_status.html
{% load static %}
{% if request.session.is_staf %}
{% include "base_staf_admin.html" %}
{% endif %}
{% if request.session.is_kurir %}
{% include "base_kurir.html" %}
{% endif %}
{% if request.session.is_user %}
{% include "base_pelanggan.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Status Transaksi</title>
</head>
<style type="text/css">
table {
  width: 50%;
  counter-reset: rowNum -1;
}
table tr {
  counter-increment: rowNum;
}
table tr td:first-child::before {
    content: counter(rowNum) ". ";
}
</style>

<body>
    <h1>Daftar Status Transaksi</h1>
    <table>
      <tr>
        <th>Email</th>
        <th>Tanggal</th>
        <th>Kode Status</th>
        <th>Timestamp</th>
        {% if request.session.is_staf %}
        <th>Action</th>
        {% endif %}
      </tr>
      {% for status_transaksi in data %}
          <tr>
            <th>{{ status_transaksi.email}}</th>
            <th>{{ status_transaksi.tanggal_transaksi}}</th>
            <th>{{ status_transaksi.kode_status}}</th>
            <th>{{ status_transaksi.timestamp}}</th>
            {% if request.session.is_staf %}
            <td>
                <a href="{% url 'transaksilaundry:update_status' email=status_transaksi.email tanggal_transaksi=status_transaksi.tanggal_transaksi %}">
                    <button>UPDATE</button>
                </a>
                <br>
                <a href="{% url 'transaksilaundry:delete_status' email=status_transaksi.email tanggal_transaksi=status_transaksi.tanggal_transaksi %}">
                    <button>DELETE</button>
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
  </table>
</div>

</body>
</html>

transaksilaundry/templates/transaksilaundry/view_transaksi.html
{% load static %}
{% if request.session.is_staf %}
{% include "base_staf_admin.html" %}
{% endif %}
{% if request.session.is_kurir %}
{% include "base_kurir.html" %}
{% endif %}
{% if request.session.is_user %}
{% include "base_pelanggan.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Transaksi</title>
</head>
<style type="text/css">
table {
  width: 50%;
  counter-reset: rowNum -1;
}
table tr {
  counter-increment: rowNum;
}
table tr td:first-child::before {
    content: counter(rowNum) ". ";
}
</style>

<body>
    <h1>Daftar Transaksi</h1>
    <table>
      <tr>
        <th>Email</th>
        <th>Tanggal</th>
        <th>Berat(kg)</th>
        <th>Total <br />Item</th>
        <th>Kode <br />Layanan</th>
        <th>Kode <br />Tarif</th>
        <th>Total Biaya</th>
        <th>Email Staff</th>
        <th>Email Kurir</th>
        {% if request.session.is_staf %}
        <th>Action</th>
        {% endif %}
      </tr>
        {% for transaksi_laundry in data %}
        <tr>
            <th>{{ transaksi_laundry.email}}</th>
            <th>{{ transaksi_laundry.tanggal}}</th>
            <th>{{ transaksi_laundry.berat}}</th>
            <th>{{ transaksi_laundry.total_item}}</th>
            <th>{{ transaksi_laundry.kode_layanan}}</th>
            <th>{{ transaksi_laundry.kode_tarif}}</th>
            <th>{{ transaksi_laundry.total_harga}}</th>
            <th>{{ transaksi_laundry.email_staf}}</th>
            <th>{{ transaksi_laundry.email_kurir_antar}}</th>
            {% if request.session.is_staf %}
            <td>
                <a href="update_transaksi/{{transaksi_laundry.email}},{{transaksi_laundry.tanggal}}">
                    <button>UPDATE</button>
                </a>
                <br>
                <a href="delete_transaksi/{{transaksi_laundry.email}},{{transaksi_laundry.tanggal}}">
                    <button>DELETE</button>
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>

</body>
</html>