item/urls.py
from django.conf.urls import url
from django.urls import include,path
from . import views

app_name='item'

urlpatterns = [
	path('',views.display_item,name='item'),
    path('create/',views.create_item,name='create-item'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main),
    path('profile/', views.profile),
]

silau/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('items/', include('item.urls')),
    path('daftarlaundry/', include('daftarlaundry.urls')),
    path('dpay/', include('topup.urls')),
    path('layanan/', include('layanan.urls')),
    path('transaksilaundry/', include('transaksilaundry.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls'))
]

transaksilaundry/urls.py
from django.urls import path

from . import views

app_name = "transaksilaundry"

urlpatterns = [
    path('', views.view_transaksi,name='view_transaksi'),
    path('update_transaksi/<str:email>,<str:tanggal>', views.update_transaksi, name='update_transaksi'),
    path('delete_transaksi/<str:email>,<str:tanggal>', views.delete_transaksi_laundry, name='delete_transaksi'),
    path('create/', views.create_transaksi, name='create_transaksi'),
    path('view_status/', views.view_status, name='view_status'),
    path('update_status/<str:email>,<str:tanggal_transaksi>', views.update_status, name='update_status'),
    path('delete_status/<str:email>,<str:tanggal_transaksi>', views.delete_status_transaksi_laundry, name='delete_status'),
    
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'profile.html')

main/templates/base_kurir.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/profile">Profile</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'transaksilaundry:view_transaksi'%}">Daftar Transaksi Laundry</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Daftar Laundry</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/items">Daftar Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/layanan">Layanan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/testimoni/">Testimoni</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksilaundry:view_status'%}">Status Transaksi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/status">Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/base_pelanggan.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/profile">Profile</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'transaksilaundry:view_transaksi'%}">Daftar Transaksi Laundry</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi TOP UP DPAY
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/dpay/create">TOP UP DPAY</a>
                    <a class="dropdown-item" href="/dpay">List TOP UP DPAY</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/daftarlaundry">Daftar Laundry</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/items">Daftar Item</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Tarif</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/layanan">Layanan</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Testimoni
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/testimoni/create">Buat Testimoni</a>
                    <a class="dropdown-item" href="/testimoni">Lihat Testimoni</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/transaksilaundry/view_status">Status Transaksi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksilaundry:view_status'%}">Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/base_staf.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/profile">Profile</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'transaksilaundry:create_transaksi'%}">Buat Transaksi Laundry</a>
                    <a class="dropdown-item" href="{% url 'transaksilaundry:view_transaksi'%}">Daftar Transaksi Laundry</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi TOP UP DPAY
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/dpay/create">TOP UP DPAY</a>
                    <a class="dropdown-item" href="/dpay">List TOP UP DPAY</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Daftar Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">                    
                    <a class="dropdown-item" href="/daftarlaundry/create">Buat Daftar Laundry</a>
                    <a class="dropdown-item" href="/daftarlaundry">Daftar Daftar Laundry</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Items
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">                    
                    <a class="dropdown-item" href="/items">Daftar Item</a>
                    <a class="dropdown-item" href="/items/create">Buat Item</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/layanan">Layanan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/testimoni/">Testimoni</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksilaundry:view_status'%}">Status Transaksi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/status">Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/base_staf_admin.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/profile">Profile</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'transaksilaundry:create_transaksi'%}">Buat Transaksi Laundry</a>
                    <a class="dropdown-item" href="{% url 'transaksilaundry:view_transaksi'%}">Daftar Transaksi Laundry</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Transaksi TOP UP DPAY
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/dpay/create">TOP UP DPAY</a>
                    <a class="dropdown-item" href="/dpay">List TOP UP DPAY</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Daftar Laundry
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">                    
                    <a class="dropdown-item" href="/daftarlaundry/create">Buat Daftar Laundry</a>
                    <a class="dropdown-item" href="/daftarlaundry">Daftar Daftar Laundry</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Items
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">                    
                    <a class="dropdown-item" href="/items">Daftar Item</a>
                    <a class="dropdown-item" href="/items/create">Buat Item</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/layanan">Layanan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/testimoni/">Testimoni</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksilaundry:view_status'%}">Status Transaksi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/status">Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

main/templates/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<title>SILAU</title>
<!-- Start of page content -->
<!-- Text landing -->
<div class="container-me">
    <div class="kerja">SILAU</div>
    
    <a href="/auth/login" class="button">
        <div>
            Login
        </div>
    </a>
    <br>
    <a href="/auth/register" class="button">
        <div>
            Register
        </div>
    </a>
</div>

main/templates/profile.html
{% load static %}
{% include "base_pelanggan.html" %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>

<style>
    table,
    th,
    td {
        border: 1px solid black;
    }

    table {
        width: 100%;
    }
</style>

</html>